language: java
jdk:
  - openjdk7
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

sudo: false

notifications:
  email:
    - mgrigorov@apache.org
  irc:
    channels:
      - "chat.freenode.net##wicket"
    template:
      - "%{repository}, %{author}, (%{commit}) : %{message} "
      - "Build details: %{build_url}"
      - "Duration: %{duration}"

env:
  global:
    - secure: "I0PbW4iQlyMO/yztGnZ/qiaMm7IS51QqAGhA5HQYKVh/ywNpQpVrpZaFRyf8OlBAemqKmOTp3EcvR225hb6RQCFilkN2vCMbMO/b7BbMRVhfV6PlpkfiuP2EehgT5vXl74tF/WbnijbvLpQppLPqbC0yYKOVplVcNEDs0LcVLfk="
    - secure: "PKgEV+4JuiCQ+69lYz8kDXLVKxn107EzGd+jq0BPxZK09LqMsvQpvkF0EZGF0gk1xXt3Gn2itVeKPbcxgufccuzVNoQnnXljvKn9+6ITTKg2HZA7UP4MrdOhhw1m+GMRKYVEdPz6qcG4FXlBfw3zgrmiZZ89K6mggPFeyf1VFDw="

cache:
  directories:
    - $HOME/.m2

install: true

before_script:
  - echo "MAVEN_OPTS='-Xmx2g -XX:MaxPermSize=512m'" > ~/.mavenrc

script:
  - "DEPLOY_OR_TEST=install"
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && DEPLOY_OR_TEST=deploy'
  - "echo DEPLOY_OR_TEST=$DEPLOY_OR_TEST"
  - "cp ./config/toolchains.xml $HOME/.m2"
  - "mvn -s sonatype-settings.xml clean $DEPLOY_OR_TEST -Dsource.skip=true -B -V --quiet"
